version: "3.8"

services:
  # --- 개발(dev) 환경 서비스 ---
  backend-dev:
    build: ./backend
    container_name: promo_backend_dev
    env_file: .env.dev # dev 환경 변수 파일 사용
    environment:
      - SPRING_PROFILES_ACTIVE=dev # dev 프로필 활성화
    ports:
      - "8080:8080"
    depends_on:
      # - db-dev
      # - redis-dev
      db-dev:
        condition: service_healthy # db-dev가 healthy 상태가 될 때까지 기다립니다.
      redis-dev:
        condition: service_started
    restart: unless-stopped

  db-dev:
    image: mysql:8.0
    container_name: promo_mysql_dev
    env_file: .env.dev # dev 환경 변수 파일 사용
    ports:
      - "3307:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=Asia/Seoul
    volumes:
      - dev-db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/init.dev.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"] # 연결 가능 상태인지 확인
      interval: 10s
      timeout: 5s
      retries: 5

  redis-dev:
    image: redis:7.2-alpine
    container_name: promo_redis_dev
    env_file: .env.dev # dev 환경 변수 파일 사용
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped

  
  kafka-dev:
    image: confluentinc/cp-kafka:7.4.0
    container_name: promo_kafka_dev
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1                        
      CLUSTER_ID: CctWeZ_kSD-6EPFq9XpVBg
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-dev:9093" 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka-dev:29092 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER 
      KAFKA_LOG_DIRS: "/tmp/kraft-data"
    volumes:
      - kafka_kraft_data:/var/lib/kafka/data

  

  # --- 운영(prod) 환경 서비스 ---
  backend-prod:
    build: ./backend
    container_name: promo_backend_prod
    env_file: .env.prod # prod 환경 변수 파일 사용
    environment:
      - SPRING_PROFILES_ACTIVE=prod # prod 프로필 활성화
    ports:
      - "80:8080"
    depends_on:
      - db-prod
      - redis-prod
    restart: unless-stopped
  
  db-prod:
    image: mysql:8.0
    container_name: promo_mysql_prod
    env_file: .env.prod # prod 환경 변수 파일 사용
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=Asia/Seoul
    volumes:
      - prod-db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: unless-stopped

  redis-prod:
    image: redis:7.2-alpine
    container_name: promo_redis_prod
    env_file: .env.prod # prod 환경 변수 파일 사용
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped

  kafka-prod:
    image: confluentinc/cp-kafka:7.4.0
    container_name: promo_kafka_prod
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1                        
      CLUSTER_ID: kL7_a9fRTY-aZc1b2d3E4f5g
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-prod:9093" 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka-prod:29092 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER 
      KAFKA_LOG_DIRS: "/tmp/kraft-data"
    volumes:
      - kafka_kraft_data:/var/lib/kafka/data
  
volumes:
  dev-db-data:
  prod-db-data:
  kafka_kraft_data:
