version: "3.8"

services:
  redis:
    image: redis:7.2-alpine
    container_name: promo_redis_local
    env_file:
      - .env.local
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"] 
    restart: unless-stopped