-- 결제 정보 테이블 추가

CREATE TABLE payments (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT NOT NULL UNIQUE  COMMENT '주문 ID',
  payment_key VARCHAR(255) NOT NULL UNIQUE COMMENT 'PG 결제 키',
  payment_method VARCHAR(20) NOT NULL COMMENT '결제 수단',
  amount DECIMAL(13, 2) NOT NULL COMMENT '결제 금액',
  status VARCHAR(20) NOT NULL COMMENT '결제 상태',
  paid_at DATETIME NULL COMMENT '결제 완료일자',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일자'
);