spring:
  application:
    name: promo
  profiles:
    active: local

  flyway:
    enabled: true  # Flyway 활성화 (기본값: true)
    baseline-on-migrate: false # 운영환경 false
    locations: classpath:db/migration # SQL 파일 위치 지정 (기본값)

