spring:
  application:
    name: promo

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:promo_db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER:promo_user}
    password: ${DB_PASS:promo_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS:redispass}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: true  # Flyway 활성화 (기본값: true)
    baseline-on-migrate: true # 이미 테이블이 있는 DB에 Flyway를 처음 적용할 때 사용
    locations: classpath:db/migration # SQL 파일 위치 지정 (기본값)

jwt:
  secret: ${JWT_SECRET:default-secret-key-c3VwZ5Rm9ySFM1Mj=}
  accessTokenExpiration: 3600 # 1시간 (초)
  refreshTokenExpiration: 604800 # 7일 (초)

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE