spring:
  application:
    name: promo
  profiles:
    active: local
  main:
    web-application-type: servlet # 웹 애플리케이션 타입 설정 (기본값: servlet)

  flyway:
    enabled: true  # Flyway 활성화 (기본값: true)
    baseline-on-migrate: false # 운영환경 false
    locations: classpath:db/migration # SQL 파일 위치 지정 (기본값)

