spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      leak-detection-threshold: 2000 # 2초

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASS}

  jpa:
    hibernate:
      ddl-auto: none # Flyway와 충돌 방지를 위해 'none'으로 변경
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    locations: classpath:db/migration,classpath:db/migration/seed

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: coupon-group # Consumer 그룹 ID 지정
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # 모든 패키지의 DTO를 신뢰하도록 설정

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 3600 # 1시간 (초)
  refreshTokenExpiration: 604800 # 7일 (초)

logging:
  file:
    name: logs/promo-dev.log
  level:
    org.springframework.web: WARN
    com.chae.promo: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.springframework.transaction: DEBUG # 트랜잭션 관련 로깅
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG # JPA 트랜잭션 관련 로깅
    org.springframework.retry: DEBUG
    org.apache.kafka: WARN
    org.apache.kafka.clients: WARN
    org.apache.kafka.clients.consumer: WARN
    org.apache.kafka.common.utils.AppInfoParser: WARN
    org.springframework.kafka: WARN
    org.springframework.kafka.listener: WARN
    org.springframework.kafka.core: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threaddump
  endpoint:
    health:
      show-details: always

app:
  redis:
    prefix: promo:dev
    use-hashtag: true # Redis 해시태그 사용 설정

naverpay:
  base-url: https://dev-pay.paygate.naver.com
  partner-id: ${NAVERPAY_PARTNER_ID}
  client-id: ${NAVERPAY_CLIENT_ID}
  client-secret: ${NAVERPAY_CLIENT_SECRET}
  chain-id: ${NAVERPAY_CHAIN_ID}

